//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SA43Team4B
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public Book()
        {
            this.IssueDetails = new HashSet<IssueDetail>();
        }
    
        public string BookISBN { get; set; }
        public string BookTitle { get; set; }
        public string BookCategory { get; set; }
        public string BookAuthor { get; set; }
        public string BookPress { get; set; }
        public string BookEdition { get; set; }
        public decimal BookPrice { get; set; }
        public int BookStockNum { get; set; }
        public int BookNumberRented { get; set; }
        public string BookWordNumber { get; set; }
        public string BookFormat { get; set; }
        public string ShelfDetails { get; set; }
    
        public virtual ICollection<IssueDetail> IssueDetails { get; set; }
    }
}
