//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SA43Team4B
{
    using System;
    using System.Collections.Generic;
    
    public partial class BooksBorrow
    {
        public string MemberName { get; set; }
        public string BookTitle { get; set; }
        public string BookCategory { get; set; }
        public System.DateTime IssueDate { get; set; }
        public string MemberType { get; set; }
    }
}
