//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SA43Team4B
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.BookIssues = new HashSet<BookIssue>();
        }
    
        public string EmpID { get; set; }
        public string EmpName { get; set; }
        public string EmpGender { get; set; }
        public string EmpPosition { get; set; }
        public string EmpPhone { get; set; }
        public string EmpPermissions { get; set; }
        public string EmpAddress { get; set; }
    
        public virtual ICollection<BookIssue> BookIssues { get; set; }
        public virtual LogInInfo LogInInfo { get; set; }
    }
}
