//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SA43Team4B
{
    using System;
    using System.Collections.Generic;
    
    public partial class IssueDetail
    {
        public string IssueID { get; set; }
        public string BookISBN { get; set; }
        public System.DateTime IssueDate { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public System.DateTime DueDate { get; set; }
        public string Remark { get; set; }
        public Nullable<int> Availability { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual BookIssue BookIssue { get; set; }
    }
}
