//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SA43Team4B
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogInInfo
    {
        public string UserID { get; set; }
        public string LoginPassword { get; set; }
        public string UserType { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Member Member { get; set; }
    }
}
