//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SA43Team4B
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberCategory
    {
        public MemberCategory()
        {
            this.Members = new HashSet<Member>();
        }
    
        public string MemberType { get; set; }
        public int NumberLimit { get; set; }
        public int DaysLimit { get; set; }
    
        public virtual ICollection<Member> Members { get; set; }
    }
}
